### ISSUE TITLE
inDimension_3f and inPosition_3f updated in Layouts

### ISSUE THREAD

**Issue by bishaljaiswal735** [dipesh7002/LuaJkrGUI#1]
<img width="789" alt="Screenshot 2024-01-12 at 11 13 17" src="https://github.com/dipesh7002/LuaJkrGUI/assets/139371224/d57ad505-7483-4a41-8d48-4e956dbfb34e">

**Comment by theanimatorspal** [comment]
Solved in Latest Commits, Closing.
